# Generated by Django 5.0.4 on 2024-06-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_department_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='works_full_name',
            new_name='works_full_time',
        ),
    ]
