# Generated by Django 5.0.4 on 2024-07-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_foodcriticrestaurantreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menureview',
            options={'ordering': ['-rating'], 'verbose_name': 'Menu Review', 'verbose_name_plural': 'Menu Reviews'},
        ),
    ]
