# Generated by Django 5.0.4 on 2024-07-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_menureview_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcriticrestaurantreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='menureview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='regularrestaurantreview',
            unique_together=set(),
        ),
    ]
