# Generated by Django 5.0.4 on 2024-07-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_foodcriticrestaurantreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcriticrestaurantreview',
            unique_together={('reviewer_name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='menureview',
            unique_together={('reviewer_name', 'menu')},
        ),
    ]
