# Generated by Django 5.0.4 on 2024-06-29 13:13

from django.db import migrations



def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')

    db_alias = schema_editor.connection.alias

    all_brands = shoe.objects.values_list('brand', flat=True).distinct()

    for brand in all_brands:
        unique_brands_model.objects.using(db_alias).create(brand_name=brand)

def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')
    unique_brands.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands)
    ]