# Generated by Django 5.0.4 on 2024-06-30 07:54

from django.db import migrations



def items_category_set(apps, schema_editor):
    items_model = apps.get_model("main_app", "Item")
    items = items_model.objects.all()
    for item in items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price >= 11 and item.price <=20:
            item.rarity = "Very Rare"
        elif item.price >= 21 and item.price <=30:
            item.rarity = "Extremely Rare"
        elif item.price >= 31:
            item.rarity = "Mega Rare"
    items_model.objects.bulk_update(items, ['rarity'])

def items_category_reset(apps, schema_editor):
    items_model = apps.get_model("main_app", "Item")
    items = items_model.objects.all()
    for item in items:
        item.rarity = 'No rarity'
        item.save()
    # items_model.objects.bulk_update(items, ['rarity'])



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [migrations.RunPython(items_category_set, items_category_reset)
    ]
