# Generated by Django 5.0.4 on 2024-06-30 13:56

from django.db import migrations

def phone_pricer(apps, schema_editor):
    MULTIPLIER = 120
    smartphone_model = apps.get_model("main_app", "Smartphone")
    smartphones = smartphone_model.objects.all()
    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * MULTIPLIER
        # smartphone.save()
    smartphone_model.objects.bulk_update(smartphones, ['price'])


def phone_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    smartphones = smartphone_model.objects.all()
    for smartphone in smartphones:
        if smartphone.price >= 750:
            smartphone.category = "Expensive"
        else:
            smartphone.category = "Cheap"
    smartphone_model.objects.bulk_update(smartphones, ['category'])

def reverser_price_cat(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "Smartphone")
    for smartphone in smartphone_model.objects.all():
        smartphone.category = smartphone_model._meta.get_field('category').default
        smartphone.price = smartphone_model._meta.get_field('price').default
        smartphone.save()

def price_and_cat(apps, schema_editor):
    phone_pricer(apps, schema_editor)
    phone_category(apps, schema_editor)




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [migrations.RunPython(price_and_cat, reverser_price_cat)
    ]
