# Generated by Django 5.0.4 on 2024-07-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_veterinarian_zookeeper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zookeeper',
            name='employee_ptr',
        ),
        migrations.RemoveField(
            model_name='zookeeper',
            name='managed_animals',
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ZooKeeper',
        ),
    ]
